### ISSUE TITLE
After filtering it opens allways the 1st image, even if clicked on the 3rd...

### ISSUE THREAD

**Issue by jcerdan** [am283721/vue-my-photos#4]
Hi,

I have set your component in a project and it looks really great!

Meanwhile, I have a problem:
I've got plenty of images that I filter by an id associated to each one. Several images have the same id.
On the first click after filtering, if for instance I get 4 images with the same 'id', and I click on the 3rd, the gallery opens but with the first one and not the 3rd I clicked on. After closing the image with 'Esc', if I click again on the 3rd then the 3rd image opens correctly.
This happens always after filtering and first click, following clicks to open the gallery opens the right image, but the first click always opens the 1st image, independently of which image is clicked.

I have set a console.log(imageName) just before the this.$refs.lightbox.show(imageName) and it prints the correct image that should be opened (the 3rd if I clicked the 3rd for instance), but it shows another image... ¿?¿?¿? 

Have someone met this problem?

Regards,

**Comment by am283721** [comment]
Hey Jordi,

Thanks for using my component, glad you like it!

The id field for each photo should be unique and not used for filtering. Are you including a 'filter' field on each image object?

Also, are the file names unique?

**Comment by jcerdan** [comment]
Hi,

yes filenames are unique for each image. In fact, images are associated to entries in a database and, each record in that database can have up to 5 images. I was adding images to lightBoxImages array as follow:

`this.lightboxImages.push({'name': element.image, 'filter': String(element.id)})`

What I am using as filter is the id of the database record not the id of the image object created to populate the lightboxImages array. That should work as expected, isn't it?

Regards

**Comment by am283721** [comment]
Are you using v-for to populate the grid of thumbnails? If so, you should use a key with a unique id for each image:

`<img v-for="thumb in filteredImages"  :key="thumb.id"`

Otherwise, you should try debugging the `show` method to see why it's not grabbing the proper index on the first click. If it can't fight the imageName in filteredImages then it defaults to the first image in the collection

`
// Find the index of the image passed to Lightbox
for(var i = 0; i < this.filteredImages.length; i++){
  if(this.filteredImages[i].name == imageName) {
    this.index = i;
    break;
  }
}
`

**Comment by jcerdan** [comment]
No, I'm not using any v-for.
ok thanks, I'll try to figure out.
Regards
